 export const productList = [
"Arbuz",
"Bakłażan",
"Botwina",
"Brokuł",
"Brukiew",
"Burak ćwikłowy",
"Burak liściowy",
"Burak zwyczajny",
"Cebula kartoflanka",
"Cebula wielopiętrowa",
"Cebula zwyczajna",
"Cebula zwyczajna Red Baron",
"Chrzan japoński",
"Ciecierzyca pospolita",
"Cnidoscolus aconitifolius",
"Coccinia grandis",
"Cukinia",
"Cykoria endywia",
"Cykoria sałatowa",
"Czosnek dęty",
"Czosnek niedźwiedzi",
"Czosnek pospolity",
"Czosnek wonny",
"Czyściec bulwiasty",
"Cebula cukrowa",
"Dynia figolistna",
"Dynia makaronowa",
"Dynia olbrzymia",
"Dynia piżmowa",
"Dynia zwyczajna",
"Fasola azuki",
"Fasola mungo",
"Fasola półksiężycowata",
"Fasola wielokwiatowa",
"Fasola złota",
"Fasola zwykła",
"Agrest",
"Ananas",
"Arbuz",
"Banan",
"Borówka",
"Brzoskwinia",
"Cytryna",
"Czereśnia",
"Grejpfrut",
"Gruszka",
"Jabłko",
"Jagoda",
"Jeżyna",
"Kokos",
"Malina",
"Mandarynka",
"Melon",
"Morela",
"Pomarańcza",
"Poziomka",
"Porzeczka",
"Renkloda",
"Śliwka",
"Truskawka",
"Winogrono",
"Wiśnia",
"Żurawina",
"Groch włoski",
"Groch zwyczajny",
"Jarmuż",
"Kabaczek",
"Kalafior",
"Kalarepa",
"Kapusta rzepak",
"Kapusta właściwa chińska",
"Kapusta właściwa pekińska",
"Karczoch hiszpański",
"Karczoch zwyczajny",
"Kiełki ",
"Kukurydza cukrowa",
"Marchew czarna",
"Marchew uprawna",
"Marchew zwyczajna",
"Melon",
"Ogórek kiwano",
"Ogórek melon",
"Ogórek siewny",
"Papryka",
"Papryka chili",
"Papryka friggitello",
"Papryka jagodowa",
"Papryka peperoni",
"Papryka roczna",
"Pasternak zwyczajny",
"Pietruszka zwyczajna",
"Piżmian jadalny",
"Pochrzyn chiński",
"Pochrzyn skrzydlaty",
"Por ",
"Rabarbar kędzierzawy",
"Rabarbar ogrodowy",
"Rokietta siewna",
"Roszpunka warzywna",
"Rzepa",
"Rzodkiew japońska",
"Rzodkiewka",
"Sałata rzymska",
"Sałata siewna",
"Seler naciowy",
"Selery zwyczajne",
"Słonecznik bulwiasty",
"Soczewica jadalna",
"Soja transgeniczna",
"Soja warzywna",
"Szczaw zwyczajny",
"Szczawik bulwiasty",
"Szczypiorek",
"Szparag lekarski",
"Szpinak warzywny",
"Wyka bób",
"Ziemniak",
"Ziemniara jadalna",
 ]